language: ruby
rvm:
  - "2.0.0"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 'rake ci SPEC_OPTS="--tag ~requires_net_connect:true"'

bundler_args: --without headless debug

before_install:
  - gem install bundler
