language: ruby
rvm:
  - "2.0.0"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 'rake spec:offline RAILS_ENV=travis SPEC_OPTS="--profile 20"'

bundler_args: --without headless debug

before_install:
  - gem install bundler
